# index:
#   path: /
#   controller: App\Controller\DefaultController::index

# test:
#   path: /test/{age<\d+>?inconnu}
#   controller: App\Controller\DefaultController::test
#   methods: [GET, POST]
#   host: localhost