# index:
#   path: /
#   controller: App\Controller\DefaultController::index

# test:
#   path: /test/{age}
#   controller: App\Controller\DefaultController::test
#   defaults:
#     age: "inconnu"
#   requirements: 
#     age: \d+
#   methods: [GET, POST]
#   host: localhost